[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/generate-code"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/grocery-list"
  to = "/.netlify/functions/app"
  status = 200